spring:
  application:
    name: sort-mapper-example
  datasource:
    url: jdbc:postgresql://localhost:5432/sort-mapper-example
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 6060
