name: Publish package to the Maven Central Repository
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Run chmod to make the gradlew file executable
        run: chmod +x ./sort-mapper/gradlew
      - name: Gradle clean
        working-directory: ./sort-mapper
        run: ./gradlew clean
      - name: Publish package to local staging directory
        working-directory: ./sort-mapper
        run: ./gradlew :publish
      - name: Publish package to maven central
        if: github.event_name == 'push'
        working-directory: ./sort-mapper
        env:
          JRELEASER_DEPLOY_MAVEN_MAVENCENTRAL_APP_USERNAME: ${{ secrets.JRELEASER_DEPLOY_MAVEN_MAVENCENTRAL_APP_USERNAME }}
          JRELEASER_DEPLOY_MAVEN_MAVENCENTRAL_APP_PASSWORD: ${{ secrets.JRELEASER_DEPLOY_MAVEN_MAVENCENTRAL_APP_PASSWORD }}
          JRELEASER_NEXUS2_USERNAME: ${{ secrets.JRELEASER_NEXUS2_USERNAME }}
          JRELEASER_NEXUS2_PASSWORD: ${{ secrets.JRELEASER_NEXUS2_PASSWORD }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew :jreleaserDeploy -DaltDeploymentRepository=local::file:./sort-mapper/target/staging-deploy --stacktrace --info
